apiVersion: v1
entries:
  alpine:
  - appVersion: "3.3"
    created: 2018-11-02T15:17:57.951378328+05:30
    description: Deploy a basic Alpine Linux pod
    digest: a822bf67c0776b108fcd9abfd6978bf0c99c0ea9667f77a3542c1d7dbe485823
    home: https://github.com/helm/helm
    name: alpine
    sources:
    - https://github.com/helm/helm
    urls:
    - https://github.com/infracloudio/helm-charts/charts/alpine-0.1.0.tgz
    version: 0.1.0
  nginx:
  - created: 2018-11-02T15:17:57.951766107+05:30
    description: A basic NGINX HTTP server
    digest: 4a6c9c501ce41afbb97f39bd74581cc2ca0aa18c8cd2ebc1fbfb18fa7c828664
    home: https://github.com/helm/helm
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: mbutcher@deis.com
      name: technosophos
    name: nginx
    sources:
    - https://hub.docker.com/_/nginx/
    urls:
    - https://github.com/infracloudio/helm-charts/charts/nginx-0.1.0.tgz
    version: 0.1.0
generated: 2018-11-02T15:17:57.950922119+05:30
